# Generated by Django 5.0.6 on 2026-04-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procesos', '0003_processmap_restructuring_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('code', models.CharField(max_length=32, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('version', models.CharField(default='1.0', max_length=32, verbose_name='Versión')),
                ('objective', models.TextField(blank=True, verbose_name='Objetivo')),
                ('scope', models.TextField(blank=True, verbose_name='Alcance')),
                ('inputs_text', models.TextField(blank=True, verbose_name='Entradas')),
                ('outputs_text', models.TextField(blank=True, verbose_name='Salidas')),
                ('last_updated', models.DateField(blank=True, null=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='procesos.process', verbose_name='Proceso')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['process', 'code', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('role_executor', models.CharField(blank=True, max_length=255, verbose_name='Cargo ejecutor')),
                ('estimated_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutos estimados')),
                ('monthly_volume', models.PositiveIntegerField(default=0, verbose_name='Volumen mensual')),
                ('input_document', models.CharField(blank=True, max_length=255, verbose_name='Documento de entrada')),
                ('output_document', models.CharField(blank=True, max_length=255, verbose_name='Documento de salida')),
                ('supporting_system', models.CharField(blank=True, max_length=255, verbose_name='Sistema de apoyo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procedimientos.procedure', verbose_name='Procedimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Paso de procedimiento',
                'verbose_name_plural': 'Pasos de procedimiento',
                'ordering': ['procedure', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['process'], name='procedimien_process_90b4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['code'], name='procedimien_code_57d000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('process', 'code', 'version')},
        ),
        migrations.AddIndex(
            model_name='procedurestep',
            index=models.Index(fields=['procedure', 'order'], name='procedimien_procedu_c0ac8b_idx'),
        ),
    ]
