# Generated by Django 5.0.6 on 2026-04-09 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_restructuring_new_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('id_type', models.CharField(default='CC', max_length=4, verbose_name='Tipo documento')),
                ('id_number', models.CharField(max_length=20, verbose_name='Número de identificación')),
                ('contract_type', models.CharField(choices=[('OPS', 'Orden de Prestación de Servicios'), ('CPS', 'Contrato de Prestación de Servicios'), ('OTRO', 'Otro tipo de contrato')], max_length=8, verbose_name='Tipo de contrato')),
                ('contract_number', models.CharField(max_length=64, verbose_name='Número de contrato')),
                ('contract_object', models.TextField(verbose_name='Objeto del contrato')),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor del contrato')),
                ('monthly_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor mensual estimado')),
                ('supervisor', models.CharField(max_length=255, verbose_name='Supervisor del contrato')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Contrato vigente')),
                ('education_level', models.CharField(blank=True, max_length=32, verbose_name='Nivel educativo')),
                ('profession', models.CharField(blank=True, max_length=255, verbose_name='Profesión/título')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Años de experiencia')),
                ('executes_permanent_functions', models.BooleanField(default=False, help_text='Verdadero si el contratista realiza funciones que deberían ser de un cargo permanente.', verbose_name='¿Ejecuta funciones permanentes?')),
                ('replaces_plant_position', models.BooleanField(default=False, help_text='Verdadero si ocupa funciones de un cargo que debería existir en planta.', verbose_name='¿Suple un cargo de planta?')),
                ('suggested_hierarchy_level', models.CharField(blank=True, choices=[('DIRECTIVO', 'Directivo'), ('ASESOR', 'Asesor'), ('PROFESIONAL', 'Profesional'), ('TECNICO', 'Técnico'), ('ASISTENCIAL', 'Asistencial')], max_length=16, verbose_name='Nivel jerárquico sugerido (si se creara cargo)')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractors', to='core.department', verbose_name='Dependencia donde presta servicios')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='core.entity')),
                ('restructuring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='core.restructuring')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
                'ordering': ['department', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ContractorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('process', models.CharField(max_length=255, verbose_name='Proceso asociado')),
                ('activity', models.CharField(max_length=500, verbose_name='Actividad / Función')),
                ('nature', models.CharField(choices=[('MISIONAL', 'Misional'), ('APOYO', 'Apoyo'), ('ESTRATEGICA', 'Estratégica'), ('TEMPORAL', 'Temporal / Proyecto')], max_length=16, verbose_name='Naturaleza')),
                ('monthly_frequency', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Frecuencia mensual')),
                ('estimated_hours_month', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas/mes estimadas')),
                ('equivalent_job_code', models.CharField(blank=True, help_text='Si esta actividad la debería hacer un cargo de planta, indicar cuál.', max_length=8, verbose_name='Código de cargo equivalente en planta')),
                ('equivalent_hierarchy_level', models.CharField(blank=True, choices=[('DIRECTIVO', 'Directivo'), ('ASESOR', 'Asesor'), ('PROFESIONAL', 'Profesional'), ('TECNICO', 'Técnico'), ('ASISTENCIAL', 'Asistencial')], max_length=16, verbose_name='Nivel jerárquico equivalente')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contratistas.contractor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Actividad de contratista',
                'verbose_name_plural': 'Actividades de contratistas',
                'ordering': ['contractor', 'process', 'activity'],
            },
        ),
        migrations.AddIndex(
            model_name='contractor',
            index=models.Index(fields=['entity', 'department'], name='contratista_entity__58b965_idx'),
        ),
        migrations.AddIndex(
            model_name='contractor',
            index=models.Index(fields=['entity', 'contract_type'], name='contratista_entity__ffea37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together={('entity', 'contract_number')},
        ),
    ]
