# Generated by Django 5.0.6 on 2026-04-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_restructuringobjective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('kind', models.CharField(choices=[('ACTO_ESTRUCTURA', 'Acto de estructura'), ('ACTO_PLANTA', 'Acto de planta'), ('MANUAL_VIGENTE', 'Manual vigente'), ('PROCEDIMIENTO', 'Procedimiento'), ('HOJA_DE_VIDA', 'Hoja de vida'), ('OFICIO_DAFP', 'Oficio DAFP'), ('CONCEPTO_DAFP', 'Concepto DAFP'), ('CONCEPTO_MINHACIENDA', 'Concepto Minhacienda'), ('SENTENCIA', 'Sentencia'), ('PRESUPUESTO', 'Presupuesto'), ('MFMP_HISTORICO', 'MFMP histórico'), ('OTRO', 'Otro')], max_length=32, verbose_name='Tipo de documento')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Archivo')),
                ('mime', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texto extraído (OCR)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.entity', verbose_name='Entidad')),
                ('restructuring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.restructuring', verbose_name='Reestructuración')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'kind'], name='documentos__entity__921069_idx'), models.Index(fields=['content_type', 'object_id'], name='documentos__content_44841d_idx'), models.Index(fields=['restructuring'], name='documentos__restruc_995aab_idx')],
            },
        ),
    ]
