# Generated by Django 5.0.6 on 2026-04-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('acronym', models.CharField(blank=True, max_length=32, verbose_name='Sigla')),
                ('order', models.CharField(choices=[('NACIONAL', 'Nacional'), ('DEPARTAMENTAL', 'Departamental'), ('DISTRITAL', 'Distrital'), ('MUNICIPAL', 'Municipal')], max_length=16, verbose_name='Orden')),
                ('municipality_category', models.CharField(choices=[('ESPECIAL', 'Especial'), ('1', 'Primera'), ('2', 'Segunda'), ('3', 'Tercera'), ('4', 'Cuarta'), ('5', 'Quinta'), ('6', 'Sexta'), ('NA', 'No aplica')], default='NA', max_length=8, verbose_name='Categoría municipal')),
                ('legal_nature', models.CharField(choices=[('MINISTERIO', 'Ministerio'), ('DEPTO_ADMIN', 'Departamento Administrativo'), ('SUPER_SIN_PJ', 'Superintendencia sin personería'), ('UAE_SIN_PJ', 'Unidad Administrativa Especial sin personería'), ('ALCALDIA', 'Alcaldía'), ('GOBERNACION', 'Gobernación'), ('SEC_DESPACHO', 'Secretaría del Despacho'), ('ESTAB_PUBLICO', 'Establecimiento Público'), ('EICE', 'Empresa Industrial y Comercial del Estado'), ('SOC_ECON_MIXTA', 'Sociedad de Economía Mixta'), ('ESE', 'Empresa Social del Estado'), ('ESP_SPD', 'Empresa Oficial de Servicios Públicos Domiciliarios'), ('INSTITUTO_CYT', 'Instituto Científico y Tecnológico'), ('SUPER_CON_PJ', 'Superintendencia con personería'), ('UAE_CON_PJ', 'Unidad Administrativa Especial con personería'), ('ESPECIAL', 'Entidad de naturaleza especial')], max_length=24, verbose_name='Naturaleza jurídica')),
                ('creation_norm', models.CharField(blank=True, max_length=255, verbose_name='Norma de creación')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Código interno')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de presentación')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.department')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.entity')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['entity', 'order', 'name'],
            },
        ),
    ]
