# Generated by Django 5.0.6 on 2026-04-04 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='approach',
            field=models.TextField(blank=True, help_text='Paso a paso, tiempo, alcance.', verbose_name='¿Qué necesita para resolverlo?'),
        ),
        migrations.AddField(
            model_name='entity',
            name='current_manual_act',
            field=models.CharField(blank=True, help_text='Acto administrativo del manual específico de funciones vigente.', max_length=255, verbose_name='Acto del manual vigente'),
        ),
        migrations.AddField(
            model_name='entity',
            name='current_payroll_act',
            field=models.CharField(blank=True, help_text='Decreto/Resolución que adopta la planta de personal actual.', max_length=255, verbose_name='Acto de planta vigente'),
        ),
        migrations.AddField(
            model_name='entity',
            name='current_structure_act',
            field=models.CharField(blank=True, help_text='Decreto/Ordenanza/Acuerdo que adopta la estructura actual.', max_length=255, verbose_name='Acto de estructura vigente'),
        ),
        migrations.AddField(
            model_name='entity',
            name='objectives',
            field=models.TextField(blank=True, help_text='Objetivos generales y específicos.', verbose_name='¿Cómo planea resolverlo?'),
        ),
        migrations.AddField(
            model_name='entity',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='Panorama actual, debilidades, carencias.', verbose_name='¿Cuál es el problema a resolver?'),
        ),
        migrations.AddField(
            model_name='entity',
            name='risks',
            field=models.TextField(blank=True, help_text='Riesgos identificados.', verbose_name='¿Qué pasa si no se resuelve?'),
        ),
        migrations.CreateModel(
            name='TimelineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Actividad')),
                ('responsible', models.CharField(blank=True, max_length=255, verbose_name='Responsable')),
                ('indicator', models.CharField(blank=True, max_length=255, verbose_name='Indicador')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En curso'), ('DONE', 'Completada'), ('BLOCKED', 'Bloqueada')], default='PENDING', max_length=16, verbose_name='Estado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.entity')),
            ],
            options={
                'verbose_name': 'Actividad del cronograma',
                'verbose_name_plural': 'Cronograma',
                'ordering': ['entity', 'order', 'start_date'],
            },
        ),
    ]
