# Generated by Django 5.0.6 on 2026-04-04 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entity_approach_entity_current_manual_act_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restructuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='Código')),
                ('reference_date', models.DateField(verbose_name='Fecha de referencia')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En curso'), ('APPROVED', 'Aprobada'), ('IMPLEMENTED', 'Implementada'), ('ARCHIVED', 'Archivada')], default='DRAFT', max_length=16, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restructurings_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restructurings', to='core.entity')),
            ],
            options={
                'verbose_name': 'Reestructuración',
                'verbose_name_plural': 'Reestructuraciones',
                'ordering': ['-reference_date', 'entity'],
                'indexes': [models.Index(fields=['entity', 'status'], name='core_restru_entity__3fe1cd_idx')],
            },
        ),
    ]
