# Generated by Django 5.0.6 on 2026-04-05 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_backfill_legacy_restructuring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntityAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Entidad con la que el usuario entra al iniciar sesion.', verbose_name='Entidad por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='core.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso usuario-entidad',
                'verbose_name_plural': 'Accesos usuario-entidad',
            },
        ),
        migrations.CreateModel(
            name='GroupModelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Permiso de grupo sobre modelo',
                'verbose_name_plural': 'Permisos de grupo sobre modelo',
                'indexes': [models.Index(fields=['group'], name='core_groupm_group_i_931804_idx'), models.Index(fields=['app_label', 'model'], name='core_groupm_app_lab_a26b94_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='groupmodelpermission',
            constraint=models.UniqueConstraint(fields=('group', 'app_label', 'model'), name='uniq_group_model_permission'),
        ),
        migrations.AddIndex(
            model_name='userentityaccess',
            index=models.Index(fields=['user'], name='core_useren_user_id_a15d45_idx'),
        ),
        migrations.AddIndex(
            model_name='userentityaccess',
            index=models.Index(fields=['entity'], name='core_useren_entity__d65701_idx'),
        ),
        migrations.AddConstraint(
            model_name='userentityaccess',
            constraint=models.UniqueConstraint(fields=('user', 'entity'), name='uniq_user_entity_access'),
        ),
        migrations.AddConstraint(
            model_name='userentityaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='uniq_user_default_entity'),
        ),
    ]
