# Generated by Django 5.0.6 on 2026-04-05 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userentityaccess_groupmodelpermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestructuringObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('kind', models.CharField(choices=[('FORTALECIMIENTO_INSTITUCIONAL', 'Fortalecimiento institucional'), ('NIVELACION_SALARIAL', 'Nivelación salarial'), ('RECLASIFICACION_EMPLEOS', 'Reclasificación de empleos'), ('CREACION_DEPENDENCIA', 'Creación de dependencia'), ('SUPRESION_DEPENDENCIA', 'Supresión de dependencia'), ('SUPRESION_EMPLEOS', 'Supresión de empleos'), ('LIQUIDACION_ENTIDAD', 'Liquidación de entidad'), ('FUSION_ENTIDADES', 'Fusión de entidades'), ('ESCISION_ENTIDAD', 'Escisión de entidad'), ('MODERNIZACION_TECNOLOGICA', 'Modernización tecnológica'), ('CUMPLIMIENTO_COMPETENCIAS', 'Cumplimiento de competencias'), ('AJUSTE_ORDEN_JUDICIAL', 'Ajuste por orden judicial'), ('CUMPLIMIENTO_LEY_617', 'Cumplimiento Ley 617/2000'), ('PLANTA_TRANSITORIA', 'Planta transitoria'), ('PLAN_CARRERA_CNSC', 'Plan de carrera CNSC'), ('AJUSTE_NOMENCLATURA', 'Ajuste de nomenclatura')], max_length=40, verbose_name='Tipo de objetivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('target_metric', models.CharField(blank=True, max_length=255, verbose_name='Métrica objetivo')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor objetivo')),
                ('indicator', models.CharField(blank=True, max_length=255, verbose_name='Indicador de seguimiento')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Prioridad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('restructuring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='core.restructuring')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Objetivo de reestructuración',
                'verbose_name_plural': 'Objetivos de reestructuración',
                'ordering': ['restructuring', 'priority', 'kind'],
                'indexes': [models.Index(fields=['restructuring'], name='core_restru_restruc_dadbdf_idx')],
                'unique_together': {('restructuring', 'kind')},
            },
        ),
    ]
