# Generated by Django 5.0.6 on 2026-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_restructuring_new_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('DESPACHO', 'Despacho'), ('SECRETARIA', 'Secretaría'), ('DIRECCION', 'Dirección'), ('SUBDIRECCION', 'Subdirección'), ('OFICINA', 'Oficina'), ('GRUPO', 'Grupo interno de trabajo'), ('AREA', 'Área / Unidad')], default='AREA', help_text='Tipo de dependencia según la jerarquía organizacional.', max_length=16, verbose_name='Nivel organizacional'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['entity', 'level'], name='core_depart_entity__eea9ca_idx'),
        ),
    ]
