# Generated by Django 5.0.6 on 2026-04-09 21:06

from django.db import migrations

DEPTH_TO_LEVEL = {
    0: 'DESPACHO',
    1: 'SECRETARIA',
    2: 'DIRECCION',
    3: 'SUBDIRECCION',
    4: 'OFICINA',
    5: 'GRUPO',
}


def assign_levels(apps, schema_editor):
    """Auto-asigna niveles según profundidad en el árbol."""
    Department = apps.get_model('core', 'Department')

    all_depts = list(Department.objects.all())
    parent_map = {d.id: d.parent_id for d in all_depts}

    def get_depth(dept_id):
        depth = 0
        current = dept_id
        visited = set()
        while current and current not in visited:
            visited.add(current)
            pid = parent_map.get(current)
            if pid:
                depth += 1
                current = pid
            else:
                break
        return depth

    for dept in all_depts:
        depth = get_depth(dept.id)
        new_level = DEPTH_TO_LEVEL.get(depth, 'AREA')
        if dept.level != new_level:
            dept.level = new_level
            dept.save(update_fields=['level'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_department_level'),
    ]

    operations = [
        migrations.RunPython(assign_levels, migrations.RunPython.noop),
    ]
