# Generated by Django 5.0.6 on 2026-04-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_entity_approach_entity_current_manual_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CURRENT', 'Actual'), ('PROPOSED', 'Propuesto')], default='CURRENT', max_length=16, verbose_name='Tipo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('reference_date', models.DateField(verbose_name='Fecha de referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_maps', to='core.entity')),
            ],
            options={
                'verbose_name': 'Mapa de procesos',
                'verbose_name_plural': 'Mapas de procesos',
                'ordering': ['-reference_date', 'entity'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('ESTRATEGICO', 'Estratégico'), ('MISIONAL', 'Misional'), ('APOYO', 'Apoyo'), ('EVALUACION', 'Evaluación y control')], max_length=16, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('required', models.BooleanField(default=True, verbose_name='¿Se requiere?')),
                ('executable_by_entity', models.BooleanField(default=True, help_text='False → candidato a tercerización.', verbose_name='¿Debe ejecutarlo la entidad?')),
                ('duplicated', models.BooleanField(default=False, verbose_name='¿Hay duplicidad con otras dependencias/entidades?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('process_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='procesos.processmap')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['process_map', 'type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValueChainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('INPUT', 'Insumo'), ('PROCESS', 'Proceso'), ('OUTPUT', 'Producto'), ('OUTCOME', 'Efecto'), ('IMPACT', 'Impacto')], max_length=16, verbose_name='Eslabón')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('process_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_chain', to='procesos.processmap')),
                ('related_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_chain_links', to='procesos.process')),
            ],
            options={
                'verbose_name': 'Eslabón de cadena de valor',
                'verbose_name_plural': 'Cadena de valor',
                'ordering': ['process_map', 'stage', 'order'],
                'indexes': [models.Index(fields=['process_map', 'stage'], name='procesos_va_process_b5b1b4_idx')],
            },
        ),
    ]
