# Generated by Django 5.0.6 on 2026-04-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobNomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('NACIONAL', 'Orden nacional (Dec. 2489/2006)'), ('TERRITORIAL', 'Orden territorial (Dec. 785/2005)')], max_length=16, verbose_name='Ámbito')),
                ('level', models.CharField(choices=[('DIRECTIVO', 'Directivo'), ('ASESOR', 'Asesor'), ('PROFESIONAL', 'Profesional'), ('TECNICO', 'Técnico'), ('ASISTENCIAL', 'Asistencial')], max_length=16, verbose_name='Nivel jerárquico')),
                ('code', models.CharField(max_length=8, verbose_name='Código')),
                ('denomination', models.CharField(max_length=255, verbose_name='Denominación')),
            ],
            options={
                'verbose_name': 'Denominación de empleo',
                'verbose_name_plural': 'Denominaciones de empleo',
                'ordering': ['scope', 'level', 'code'],
                'unique_together': {('scope', 'code', 'denomination')},
            },
        ),
    ]
