# Generated by Django 5.0.6 on 2026-04-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='officialconsultation',
            new_name='consultas_o_restruc_8a954d_idx',
            old_name='consultas_restr_target_idx',
        ),
    ]
