# Generated by Django 5.0.6 on 2026-04-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del estudio')),
                ('reference_date', models.DateField(verbose_name='Fecha de referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_matrices', to='core.entity')),
            ],
            options={
                'verbose_name': 'Matriz de cargas de trabajo',
                'verbose_name_plural': 'Matrices de cargas de trabajo',
                'ordering': ['-reference_date', 'entity'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=255, verbose_name='Proceso')),
                ('activity', models.CharField(max_length=500, verbose_name='Actividad')),
                ('procedure', models.CharField(blank=True, max_length=500, verbose_name='Procedimiento')),
                ('hierarchy_level', models.CharField(choices=[('DIRECTIVO', 'Directivo'), ('ASESOR', 'Asesor'), ('PROFESIONAL', 'Profesional'), ('TECNICO', 'Técnico'), ('ASISTENCIAL', 'Asistencial')], max_length=16, verbose_name='Nivel jerárquico')),
                ('requirements', models.TextField(blank=True, verbose_name='Requisitos de estudio y experiencia')),
                ('job_denomination', models.CharField(max_length=255, verbose_name='Denominación del empleo')),
                ('job_code', models.CharField(blank=True, max_length=8, verbose_name='Código')),
                ('job_grade', models.CharField(blank=True, max_length=8, verbose_name='Grado')),
                ('main_purpose', models.TextField(blank=True, help_text='Verbo + objeto + condición.', verbose_name='Propósito principal del empleo')),
                ('monthly_frequency', models.DecimalField(decimal_places=4, help_text='Veces/mes. Fracciones: anual=0.0833, semestral=0.1667, etc.', max_digits=10, verbose_name='Frecuencia mensual')),
                ('t_min', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tiempo mínimo (h)')),
                ('t_usual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tiempo usual (h)')),
                ('t_max', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tiempo máximo (h)')),
                ('standard_time', models.DecimalField(decimal_places=4, editable=False, max_digits=10, verbose_name='Tiempo estándar (h)')),
                ('hh_month', models.DecimalField(decimal_places=4, editable=False, max_digits=10, verbose_name='Horas-hombre/mes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workload_entries', to='core.department')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cargas.workloadmatrix')),
            ],
            options={
                'verbose_name': 'Actividad medida',
                'verbose_name_plural': 'Actividades medidas',
                'ordering': ['department', 'process', 'activity'],
                'indexes': [models.Index(fields=['matrix', 'department'], name='cargas_work_matrix__fd1271_idx'), models.Index(fields=['matrix', 'hierarchy_level'], name='cargas_work_matrix__47e416_idx'), models.Index(fields=['matrix', 'job_code'], name='cargas_work_matrix__0a1abb_idx')],
            },
        ),
    ]
