# Generated by Django 5.0.6 on 2026-04-05 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0003_workloadmatrix_restructuring_required'),
        ('procedimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadentry',
            name='procedure_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_entries', to='procedimientos.procedurestep', verbose_name='Paso de procedimiento'),
        ),
    ]
