# Generated by Django 5.0.6 on 2026-04-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_restructuringobjective'),
        ('procesos', '0003_processmap_restructuring_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('norm', models.CharField(max_length=255, verbose_name='Norma')),
                ('article', models.CharField(blank=True, max_length=64, verbose_name='Artículo')),
                ('mandate_text', models.TextField(verbose_name='Texto del mandato')),
                ('kind', models.CharField(choices=[('EJECUCION', 'Ejecución'), ('REGULACION', 'Regulación'), ('VIGILANCIA', 'Vigilancia'), ('FOMENTO', 'Fomento'), ('OTRO', 'Otro')], max_length=16, verbose_name='Tipo')),
                ('is_constitutional', models.BooleanField(default=False, verbose_name='¿Es constitucional?')),
                ('assigned_to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='core.department', verbose_name='Dependencia responsable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_mandates', to='core.entity', verbose_name='Entidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Mandato legal',
                'verbose_name_plural': 'Mandatos legales',
                'ordering': ['entity', 'norm', 'article'],
            },
        ),
        migrations.CreateModel(
            name='MandateCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('coverage', models.CharField(choices=[('FULL', 'Plena'), ('PARTIAL', 'Parcial'), ('NONE', 'Ninguna')], max_length=8, verbose_name='Cobertura')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='mandatos.legalmandate', verbose_name='Mandato')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandate_compliances', to='procesos.process', verbose_name='Proceso')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Cumplimiento de mandato',
                'verbose_name_plural': 'Cumplimientos de mandatos',
            },
        ),
        migrations.AddIndex(
            model_name='legalmandate',
            index=models.Index(fields=['entity', 'kind'], name='mandatos_le_entity__7996cf_idx'),
        ),
        migrations.AddIndex(
            model_name='legalmandate',
            index=models.Index(fields=['norm'], name='mandatos_le_norm_6777f1_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatecompliance',
            index=models.Index(fields=['mandate'], name='mandatos_ma_mandate_983dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='mandatecompliance',
            index=models.Index(fields=['process'], name='mandatos_ma_process_e52b13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mandatecompliance',
            unique_together={('mandate', 'process')},
        ),
    ]
