# Generated by Django 5.0.6 on 2026-04-05 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_restructuringobjective'),
        ('planta', '0003_payrollplan_restructuring_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('id_type', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil')], max_length=4, verbose_name='Tipo de documento')),
                ('id_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario')], max_length=2, verbose_name='Sexo')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Tiene discapacidad')),
                ('disability_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='% de discapacidad')),
                ('is_head_of_household', models.BooleanField(default=False, verbose_name='Cabeza de hogar')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.entity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['entity', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PRIMARIA', 'Primaria'), ('BACHILLERATO', 'Bachillerato'), ('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('PREGRADO', 'Pregrado / Profesional'), ('ESPECIALIZACION', 'Especialización'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20, verbose_name='Nivel educativo')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('program', models.CharField(max_length=200, verbose_name='Programa')),
                ('title', models.CharField(max_length=200, verbose_name='Título obtenido')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de grado')),
                ('credential_number', models.CharField(blank=True, max_length=64, verbose_name='Número de tarjeta profesional')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='talento.employee')),
            ],
            options={
                'verbose_name': 'Educación del empleado',
                'verbose_name_plural': 'Educación de empleados',
                'ordering': ['employee', 'level'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Puntaje')),
                ('result', models.CharField(choices=[('SOBRESALIENTE', 'Sobresaliente'), ('SATISFACTORIO', 'Satisfactorio'), ('NO_SATISFACTORIO', 'No satisfactorio')], max_length=20, verbose_name='Resultado')),
                ('evaluator', models.CharField(max_length=200, verbose_name='Evaluador')),
                ('at', models.DateField(verbose_name='Fecha de evaluación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='talento.employee')),
            ],
            options={
                'verbose_name': 'Evaluación de desempeño',
                'verbose_name_plural': 'Evaluaciones de desempeño',
                'ordering': ['employee', '-year'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=200, verbose_name='Empleador')),
                ('position_name', models.CharField(max_length=200, verbose_name='Cargo desempeñado')),
                ('sector', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('MIXTO', 'Mixto'), ('INDEPENDIENTE', 'Independiente'), ('OTRO', 'Otro')], max_length=20, verbose_name='Sector')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('is_current', models.BooleanField(default=False, verbose_name='Empleo actual')),
                ('is_public_sector', models.BooleanField(default=False, verbose_name='Sector público')),
                ('functions', models.TextField(blank=True, verbose_name='Funciones desempeñadas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='talento.employee')),
            ],
            options={
                'verbose_name': 'Experiencia laboral',
                'verbose_name_plural': 'Experiencias laborales',
                'ordering': ['employee', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Tema')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Horas')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('cert', models.CharField(blank=True, max_length=64, verbose_name='Número de certificado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='talento.employee')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['employee', '-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('appointment_type', models.CharField(choices=[('CARRERA', 'Carrera administrativa'), ('LNR', 'Libre nombramiento y remoción'), ('PROVISIONAL', 'Provisional'), ('TEMPORAL', 'Temporal'), ('SUPERNUMERARIO', 'Supernumerario'), ('TRABAJADOR_OFICIAL', 'Trabajador oficial')], max_length=20, verbose_name='Forma de vinculación')),
                ('appointment_date', models.DateField(verbose_name='Fecha de posesión')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('termination_reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo de retiro')),
                ('administrative_status', models.CharField(choices=[('ACTIVO', 'Activo'), ('VACACIONES', 'En vacaciones'), ('LICENCIA_REMUNERADA', 'Licencia remunerada'), ('LICENCIA_NO_REMUNERADA', 'Licencia no remunerada'), ('COMISION_SERVICIOS', 'Comisión de servicios'), ('COMISION_ESTUDIO', 'Comisión de estudios'), ('ENCARGO', 'En encargo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=25, verbose_name='Situación administrativa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vigente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='talento.employee')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='core.entity')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment_records', to='planta.payrollposition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Vinculación laboral',
                'verbose_name_plural': 'Vinculaciones laborales',
                'ordering': ['employee', '-appointment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['entity'], name='talento_emp_entity__80bba7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['id_number'], name='talento_emp_id_numb_0f7e24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('entity', 'id_type', 'id_number')},
        ),
        migrations.AddIndex(
            model_name='employeeeducation',
            index=models.Index(fields=['employee'], name='talento_emp_employe_d7ae90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeevaluation',
            unique_together={('employee', 'year')},
        ),
        migrations.AddIndex(
            model_name='employeeexperience',
            index=models.Index(fields=['employee'], name='talento_emp_employe_1f8efc_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentrecord',
            index=models.Index(fields=['employee'], name='talento_emp_employe_977a59_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentrecord',
            index=models.Index(fields=['position'], name='talento_emp_positio_cf1d18_idx'),
        ),
    ]
