# Generated by Django 5.0.6 on 2026-04-09 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargas', '0005_manualfuncionesoverride'),
        ('core', '0007_restructuring_new_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de acceso')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('id_number', models.CharField(max_length=20, verbose_name='Número de identificación')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('link_type', models.CharField(choices=[('CARRERA', 'Carrera administrativa'), ('LNR', 'Libre nombramiento y remoción'), ('PROVISIONAL', 'Provisional'), ('TEMPORAL', 'Temporal'), ('SUPERNUMERARIO', 'Supernumerario'), ('TRABAJADOR_OFICIAL', 'Trabajador oficial'), ('OPS', 'Orden de Prestación de Servicios'), ('CPS', 'Contrato de Prestación de Servicios'), ('OTRO', 'Otro')], max_length=24, verbose_name='Tipo de vinculación')),
                ('contract_number', models.CharField(blank=True, max_length=64, verbose_name='Número de contrato')),
                ('contract_object', models.TextField(blank=True, verbose_name='Objeto del contrato')),
                ('contract_supervisor', models.CharField(blank=True, max_length=255, verbose_name='Supervisor del contrato')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='Fecha inicio contrato')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='Fecha fin contrato')),
                ('job_denomination', models.CharField(blank=True, max_length=255, verbose_name='Denominación del empleo/cargo')),
                ('job_code', models.CharField(blank=True, max_length=8, verbose_name='Código')),
                ('job_grade', models.CharField(blank=True, max_length=8, verbose_name='Grado')),
                ('submitted', models.BooleanField(default=False, verbose_name='Encuesta diligenciada')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_participants', to='core.department', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=255, verbose_name='Proceso')),
                ('activity', models.CharField(max_length=500, verbose_name='Actividad / Función')),
                ('procedure', models.CharField(blank=True, max_length=500, verbose_name='Procedimiento')),
                ('hierarchy_level', models.CharField(blank=True, choices=[('DIRECTIVO', 'Directivo'), ('ASESOR', 'Asesor'), ('PROFESIONAL', 'Profesional'), ('TECNICO', 'Técnico'), ('ASISTENCIAL', 'Asistencial')], help_text='Opcional. El técnico puede ajustarlo luego.', max_length=16, verbose_name='Nivel jerárquico')),
                ('monthly_frequency', models.DecimalField(decimal_places=4, help_text='Veces al mes que realiza esta actividad.', max_digits=10, verbose_name='Frecuencia mensual')),
                ('t_min', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tiempo mínimo (horas)')),
                ('t_usual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tiempo usual (horas)')),
                ('t_max', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tiempo máximo (horas)')),
                ('standard_time', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10, verbose_name='Tiempo estándar (h)')),
                ('hh_month', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10, verbose_name='Horas-hombre/mes')),
                ('is_core_activity', models.BooleanField(default=False, help_text='Si la actividad es misional de la entidad (no de apoyo/administrativa).', verbose_name='¿Es actividad misional?')),
                ('should_be_in_plant', models.BooleanField(blank=True, default=None, help_text='Opinión del participante: ¿esta actividad requiere un cargo permanente?', null=True, verbose_name='¿Debería ser cargo de planta?')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobada por el técnico')),
                ('consolidated', models.BooleanField(default=False, verbose_name='Consolidada en matriz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='encuestas.surveyparticipant')),
            ],
            options={
                'verbose_name': 'Actividad de encuesta',
                'verbose_name_plural': 'Actividades de encuesta',
                'ordering': ['participant', 'process', 'activity'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la encuesta')),
                ('description', models.TextField(blank=True, default='Por favor registre todas las actividades que realiza en su cargo/contrato, indicando la frecuencia mensual y los tiempos estimados.', verbose_name='Instrucciones para los participantes')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='DRAFT', max_length=16, verbose_name='Estado')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_surveys', to='core.entity')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cargas.workloadmatrix')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Encuesta de cargas',
                'verbose_name_plural': 'Encuestas de cargas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='surveyparticipant',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='encuestas.workloadsurvey'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyparticipant',
            unique_together={('survey', 'id_number')},
        ),
    ]
