# Generated by Django 5.0.6 on 2026-04-04 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_entity_approach_entity_current_manual_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('reference_date', models.DateField(verbose_name='Fecha de referencia')),
                ('mission', models.TextField(blank=True, verbose_name='Misión / objeto social')),
                ('vision', models.TextField(blank=True, verbose_name='Visión')),
                ('functions_analysis', models.TextField(blank=True, help_text='Variaciones en el tiempo, duplicidades, posibilidad de tercerización.', verbose_name='Análisis de funciones generales')),
                ('duplications', models.TextField(blank=True, verbose_name='Duplicidades identificadas')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.entity')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-reference_date', 'entity'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('ECONOMICO', 'Económico'), ('POLITICO', 'Político'), ('SOCIAL', 'Social'), ('TECNOLOGICO', 'Tecnológico'), ('CULTURAL', 'Cultura organizacional'), ('OTRO', 'Otro')], max_length=16, verbose_name='Dimensión')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('impact', models.SmallIntegerField(choices=[(-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo')], default=0, verbose_name='Impacto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='diagnostico.diagnosis')),
            ],
            options={
                'verbose_name': 'Análisis de entorno',
                'verbose_name_plural': 'Análisis de entornos',
                'ordering': ['diagnosis', 'dimension', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LegalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.CharField(max_length=255, verbose_name='Norma / jurisprudencia')),
                ('article', models.CharField(blank=True, max_length=128, verbose_name='Artículo / providencia')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Tema')),
                ('correlated_decision', models.TextField(help_text='Obligatorio: no se permite citar normas descontextualizadas.', verbose_name='Decisión del rediseño que la invoca')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_refs', to='diagnostico.diagnosis')),
            ],
            options={
                'verbose_name': 'Referencia legal',
                'verbose_name_plural': 'Marco legal correlacionado',
                'ordering': ['diagnosis', 'order', 'norm'],
            },
        ),
        migrations.CreateModel(
            name='SwotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Fortaleza'), ('D', 'Debilidad'), ('O', 'Oportunidad'), ('A', 'Amenaza')], max_length=1, verbose_name='Tipo')),
                ('dimension', models.CharField(choices=[('DIRECTIVA', 'Directiva'), ('COMPETITIVA', 'Competitiva'), ('TECNICA', 'Técnica'), ('TECNOLOGICA', 'Tecnológica'), ('TH', 'Talento humano')], max_length=16, verbose_name='Dimensión')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2, verbose_name='Prioridad')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swot_items', to='diagnostico.diagnosis')),
            ],
            options={
                'verbose_name': 'Ítem DOFA',
                'verbose_name_plural': 'Ítems DOFA',
                'ordering': ['diagnosis', 'type', 'dimension', 'order'],
                'indexes': [models.Index(fields=['diagnosis', 'type', 'dimension'], name='diagnostico_diagnos_a6d64b_idx')],
            },
        ),
    ]
