# Generated by Django 5.0.6 on 2026-04-05 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_userentityaccess_groupmodelpermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=8)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='core.entity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de cambio',
                'verbose_name_plural': 'Historial de cambios',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['app_label', 'model'], name='common_chan_app_lab_8cb2c7_idx'), models.Index(fields=['entity', '-at'], name='common_chan_entity__f07217_idx'), models.Index(fields=['user', '-at'], name='common_chan_user_id_8d0c49_idx'), models.Index(fields=['object_id'], name='common_chan_object__4ce357_idx')],
            },
        ),
    ]
