# Generated by Django 5.0.6 on 2026-04-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_entity_approach_entity_current_manual_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DECRETO', 'Decreto'), ('ORDENANZA', 'Ordenanza'), ('ACUERDO', 'Acuerdo'), ('RESOLUCION', 'Resolución'), ('ESTATUTOS', 'Estatutos')], max_length=16, verbose_name='Tipo')),
                ('scope', models.CharField(choices=[('NACIONAL', 'Orden Nacional'), ('DEPARTAMENTAL', 'Departamental'), ('MUNICIPAL', 'Municipal / Distrital'), ('DESCENTRALIZADO', 'Entidad descentralizada')], max_length=16, verbose_name='Ámbito')),
                ('topic', models.CharField(choices=[('ESTRUCTURA', 'Modificación de estructura'), ('PLANTA', 'Adopción / modificación de planta'), ('MANUAL', 'Manual específico de funciones'), ('SALARIAL', 'Escala salarial'), ('SUPRESION', 'Supresión de empleos'), ('LIQUIDACION', 'Supresión / liquidación de entidad')], max_length=16, verbose_name='Tema')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('body', models.TextField(help_text='Placeholders estilo {entity_name}, {date}, {problem_statement}, etc.', verbose_name='Cuerpo con placeholders')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de acto',
                'verbose_name_plural': 'Plantillas de actos',
                'ordering': ['scope', 'kind', 'topic', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('kind', models.CharField(choices=[('DECRETO', 'Decreto'), ('ORDENANZA', 'Ordenanza'), ('ACUERDO', 'Acuerdo'), ('RESOLUCION', 'Resolución'), ('ESTATUTOS', 'Estatutos')], max_length=16, verbose_name='Tipo')),
                ('topic', models.CharField(choices=[('ESTRUCTURA', 'Modificación de estructura'), ('PLANTA', 'Adopción / modificación de planta'), ('MANUAL', 'Manual específico de funciones'), ('SALARIAL', 'Escala salarial'), ('SUPRESION', 'Supresión de empleos'), ('LIQUIDACION', 'Supresión / liquidación de entidad')], max_length=16, verbose_name='Tema')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('REVIEW', 'En revisión'), ('ISSUED', 'Expedido'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=16, verbose_name='Estado')),
                ('act_number', models.CharField(blank=True, max_length=64, verbose_name='Número del acto')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fecha de expedición')),
                ('signed_by', models.CharField(blank=True, max_length=255, verbose_name='Firmado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_drafts', to='core.entity')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='actos.acttemplate')),
            ],
            options={
                'verbose_name': 'Borrador de acto',
                'verbose_name_plural': 'Borradores de actos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
