# Generated by Django 5.0.6 on 2026-04-09 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_assign_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Dependencia')),
                ('role_in_team', models.CharField(choices=[('COORDINADOR', 'Coordinador'), ('PLANEACION', 'Planeación'), ('JURIDICO', 'Jurídico'), ('FINANCIERO', 'Financiero'), ('TH', 'Talento Humano'), ('TECNICO', 'Técnico'), ('OTRO', 'Otro')], max_length=16, verbose_name='Rol en el equipo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('restructuring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.restructuring')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Miembro del equipo técnico',
                'verbose_name_plural': 'Miembros del equipo técnico',
                'ordering': ['role_in_team', 'name'],
            },
        ),
    ]
