# Generated by Django 5.0.6 on 2026-04-04 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_entity_approach_entity_current_manual_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('id_type', models.CharField(default='CC', max_length=8, verbose_name='Tipo documento')),
                ('id_number', models.CharField(max_length=32, verbose_name='Número documento')),
                ('job_denomination', models.CharField(blank=True, max_length=255, verbose_name='Cargo actual')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Dependencia')),
                ('protection_type', models.CharField(choices=[('MADRE_CABEZA', 'Madre cabeza de familia'), ('PADRE_CABEZA', 'Padre cabeza de familia'), ('DISCAPACIDAD', 'Persona con discapacidad'), ('PRE_PENSIONADO', 'Pre-pensionado'), ('EMBARAZO', 'Empleada en embarazo'), ('LACTANCIA', 'Empleada en lactancia'), ('FUERO_SINDICAL', 'Empleado con fuero sindical')], max_length=16, verbose_name='Tipo de protección')),
                ('protection_start', models.DateField(blank=True, null=True, verbose_name='Fecha inicio de protección')),
                ('protection_end', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de fin')),
                ('evidence', models.TextField(blank=True, help_text='Describe el soporte que acredita la condición.', verbose_name='Soporte documental')),
                ('active', models.BooleanField(default=True, verbose_name='Protección vigente')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_employees', to='core.entity')),
            ],
            options={
                'verbose_name': 'Empleado con protección',
                'verbose_name_plural': 'Retén social',
                'ordering': ['entity', 'full_name'],
                'indexes': [models.Index(fields=['entity', 'protection_type', 'active'], name='reten_prote_entity__160279_idx')],
            },
        ),
    ]
