# Generated by Django 5.0.6 on 2026-04-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reten', '0001_initial'),
        ('talento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedemployee',
            name='employee_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protection_records', to='talento.employee', verbose_name='Hoja de vida vinculada'),
        ),
        migrations.AddField(
            model_name='protectedemployee',
            name='is_manual',
            field=models.BooleanField(default=True, verbose_name='Registro manual'),
        ),
    ]
