# Generated by Django 5.0.6 on 2026-04-04 21:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_entity_approach_entity_current_manual_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CURRENT', 'Planta actual'), ('PROPOSED', 'Planta propuesta')], max_length=16, verbose_name='Tipo')),
                ('structure', models.CharField(choices=[('GLOBAL', 'Global'), ('STRUCTURAL', 'Estructural')], default='GLOBAL', max_length=16, verbose_name='Estructura')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('reference_date', models.DateField(verbose_name='Fecha de referencia')),
                ('adopted_by', models.CharField(blank=True, help_text='Decreto/Resolución/Acuerdo. Solo para planta actual.', max_length=255, verbose_name='Acto administrativo que la adopta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_plans', to='core.entity')),
            ],
            options={
                'verbose_name': 'Planta de personal',
                'verbose_name_plural': 'Plantas de personal',
                'ordering': ['-reference_date', 'entity', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_level', models.CharField(choices=[('DIRECTIVO', 'Directivo'), ('ASESOR', 'Asesor'), ('PROFESIONAL', 'Profesional'), ('TECNICO', 'Técnico'), ('ASISTENCIAL', 'Asistencial')], max_length=16, verbose_name='Nivel jerárquico')),
                ('denomination', models.CharField(max_length=255, verbose_name='Denominación del empleo')),
                ('code', models.CharField(blank=True, max_length=8, verbose_name='Código')),
                ('grade', models.CharField(blank=True, max_length=8, verbose_name='Grado')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Asignación básica mensual')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('department', models.ForeignKey(blank=True, help_text='Solo aplica en planta estructural.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_positions', to='core.department')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='planta.payrollplan')),
            ],
            options={
                'verbose_name': 'Cargo de planta',
                'verbose_name_plural': 'Cargos de planta',
                'ordering': ['plan', 'hierarchy_level', 'code', 'grade'],
                'indexes': [models.Index(fields=['plan', 'hierarchy_level'], name='planta_payr_plan_id_e6aea3_idx'), models.Index(fields=['plan', 'code', 'grade'], name='planta_payr_plan_id_23e8c5_idx')],
            },
        ),
    ]
