# Generated by Django 5.0.6 on 2026-04-04 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restructuring'),
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollplan',
            name='restructuring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_plans', to='core.restructuring'),
        ),
    ]
