# Generated by Django 5.0.6 on 2026-04-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_restructuringobjective'),
        ('planta', '0003_payrollplan_restructuring_required'),
        ('talento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollposition',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_held', to='talento.employee', verbose_name='Empleado ocupante'),
        ),
        migrations.AddIndex(
            model_name='payrollposition',
            index=models.Index(fields=['occupant'], name='planta_payr_occupan_f9d473_idx'),
        ),
    ]
