# Generated by Django 5.0.6 on 2026-04-05 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_restructuring_new_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('kind', models.CharField(choices=[('TRANSITION', 'Transición de estado'), ('VALIDATION_ERROR', 'Validación en rojo'), ('CONSULTATION_DUE', 'Consulta por vencer'), ('DOCUMENT_NEW', 'Documento nuevo'), ('ASSIGNMENT', 'Tarea asignada'), ('SYSTEM', 'Sistema')], max_length=24, verbose_name='Tipo')),
                ('message', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('link', models.CharField(blank=True, help_text='Ruta relativa del frontend (ej. /reestructuraciones/1/gobierno).', max_length=255, verbose_name='Ruta frontend')),
                ('read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.entity', verbose_name='Entidad')),
                ('restructuring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.restructuring', verbose_name='Reestructuración')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificacio_user_id_22e37d_idx'), models.Index(fields=['user', 'read'], name='notificacio_user_id_d7a7bc_idx')],
            },
        ),
    ]
