# Generated by Django 5.0.6 on 2026-04-05 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_restructuringobjective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitySalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('base_scale_year', models.PositiveIntegerField(verbose_name='Año base de escala')),
                ('regime', models.CharField(choices=[('TERRITORIAL_GENERAL', 'Territorial general'), ('NACIONAL_GENERAL', 'Nacional general'), ('TRABAJADOR_OFICIAL', 'Trabajador oficial'), ('OTRO', 'Otro')], max_length=24, verbose_name='Régimen prestacional')),
                ('extra_components', models.JSONField(default=dict, verbose_name='Componentes extra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to='core.entity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración salarial de entidad',
                'verbose_name_plural': 'Configuraciones salariales',
            },
        ),
        migrations.CreateModel(
            name='PrestationalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('TERRITORIAL_GENERAL', 'Territorial general'), ('NACIONAL_GENERAL', 'Nacional general'), ('TRABAJADOR_OFICIAL', 'Trabajador oficial'), ('OTRO', 'Otro')], max_length=24, verbose_name='Régimen')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('factor', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Factor prestacional')),
                ('detail', models.JSONField(default=dict, verbose_name='Detalle de componentes')),
            ],
            options={
                'verbose_name': 'Factor prestacional',
                'verbose_name_plural': 'Factores prestacionales',
                'ordering': ['regime', '-year'],
                'indexes': [models.Index(fields=['year'], name='nomina_pres_year_f5f7d1_idx')],
                'unique_together': {('regime', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('NACIONAL', 'Nacional'), ('DEPARTAMENTAL', 'Departamental'), ('DISTRITAL', 'Distrital'), ('MUNICIPAL', 'Municipal')], max_length=16, verbose_name='Orden')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('level', models.CharField(choices=[('DIRECTIVO', 'Directivo'), ('ASESOR', 'Asesor'), ('PROFESIONAL', 'Profesional'), ('TECNICO', 'Técnico'), ('ASISTENCIAL', 'Asistencial')], max_length=16, verbose_name='Nivel')),
                ('grade', models.CharField(max_length=8, verbose_name='Grado')),
                ('code', models.CharField(max_length=8, verbose_name='Código')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Asignación básica')),
            ],
            options={
                'verbose_name': 'Escala salarial',
                'verbose_name_plural': 'Escala salarial',
                'ordering': ['order', 'year', 'level', 'code', 'grade'],
                'indexes': [models.Index(fields=['order', 'year', 'level'], name='nomina_sala_order_9aa859_idx')],
                'unique_together': {('order', 'year', 'level', 'code', 'grade')},
            },
        ),
    ]
