# Generated by Django 5.0.6 on 2026-04-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JotaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('bot_name', models.CharField(default='Jota', max_length=64, verbose_name='Nombre del bot')),
                ('welcome_message', models.TextField(default='¡Hola! Soy **Jota**, tu asistente de ayuda. Pregúntame sobre los módulos de ReEstructura.Gov.', verbose_name='Mensaje de bienvenida')),
                ('fallback_message', models.TextField(default='No encontré información sobre eso. Prueba preguntando por "matriz de cargas", "planta", "diagnóstico" o "actos administrativos".', verbose_name='Mensaje fallback')),
                ('suggested_questions', models.TextField(blank=True, default='¿Qué es la matriz de cargas?\n¿Cómo creo una reestructuración?\n¿Cómo genero el manual de funciones?\n¿Qué es el retén social?', verbose_name='Preguntas sugeridas (una por línea)')),
                ('position', models.CharField(choices=[('bottom-right', 'Abajo a la derecha'), ('bottom-left', 'Abajo a la izquierda')], default='bottom-right', max_length=16, verbose_name='Posición')),
                ('primary_color', models.CharField(default='#0e7490', help_text='Color del botón flotante.', max_length=16, verbose_name='Color primario (hex)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Jota',
                'verbose_name_plural': 'Configuración de Jota',
            },
        ),
        migrations.CreateModel(
            name='JotaIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('category', models.CharField(blank=True, help_text='Ej.: Módulos, Flujo general, Problemas comunes.', max_length=64, verbose_name='Categoría')),
                ('keywords', models.TextField(help_text='Separa por comas o saltos de línea. Coincidencia por subcadena, sin tildes, en minúsculas.', verbose_name='Palabras clave')),
                ('answer', models.TextField(help_text='Markdown ligero: **negrita**, *itálica*, - listas, [texto](/ruta).', verbose_name='Respuesta')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Mayor = gana en empates.', verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intención de Jota',
                'verbose_name_plural': 'Intenciones de Jota',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='jota_jotain_is_acti_bda951_idx')],
            },
        ),
    ]
