# Generated by Django 5.0.6 on 2026-04-05 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_restructuringobjective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('base_year', models.PositiveIntegerField(verbose_name='Año base')),
                ('horizon_years', models.PositiveIntegerField(default=10, verbose_name='Años de horizonte')),
                ('approved_by', models.CharField(blank=True, max_length=255, verbose_name='Aprobado por')),
                ('approved_at', models.DateField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfmps', to='core.entity', verbose_name='Entidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'MFMP',
                'verbose_name_plural': 'MFMPs',
                'ordering': ['-base_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MFMPDebtProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('outstanding_debt', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Saldo de deuda')),
                ('debt_service', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Servicio de deuda')),
                ('new_disbursements', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nuevos desembolsos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('mfmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='mfmp.mfmp', verbose_name='MFMP')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Proyección de deuda MFMP',
                'verbose_name_plural': 'Proyecciones de deuda MFMP',
                'ordering': ['mfmp', 'year'],
            },
        ),
        migrations.CreateModel(
            name='MFMPExpenseProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('concept', models.CharField(choices=[('FUNCIONAMIENTO_PERSONAL', 'Funcionamiento — Personal'), ('FUNCIONAMIENTO_GENERALES', 'Funcionamiento — Gastos generales'), ('FUNCIONAMIENTO_TRANSFERENCIAS', 'Funcionamiento — Transferencias'), ('SERVICIO_DEUDA', 'Servicio de la deuda'), ('INVERSION', 'Inversión'), ('OTROS', 'Otros')], max_length=32, verbose_name='Concepto')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('mfmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='mfmp.mfmp', verbose_name='MFMP')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Proyección de gastos MFMP',
                'verbose_name_plural': 'Proyecciones de gastos MFMP',
                'ordering': ['mfmp', 'year', 'concept'],
            },
        ),
        migrations.CreateModel(
            name='MFMPIncomeProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('concept', models.CharField(choices=[('TRIBUTARIOS', 'Tributarios'), ('NO_TRIBUTARIOS', 'No tributarios'), ('TRANSFERENCIAS_SGP', 'Transferencias SGP'), ('TRANSFERENCIAS_OTRAS', 'Transferencias otras'), ('REGALIAS', 'Regalías'), ('COFINANCIACION', 'Cofinanciación'), ('CREDITO', 'Crédito'), ('RECURSOS_BALANCE', 'Recursos de balance'), ('OTROS', 'Otros')], max_length=32, verbose_name='Concepto')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('mfmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='mfmp.mfmp', verbose_name='MFMP')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Proyección de ingresos MFMP',
                'verbose_name_plural': 'Proyecciones de ingresos MFMP',
                'ordering': ['mfmp', 'year', 'concept'],
            },
        ),
        migrations.CreateModel(
            name='MFMPScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('deltas_json', models.JSONField(blank=True, default=dict, verbose_name='Deltas JSON')),
                ('is_baseline', models.BooleanField(default=False, verbose_name='Es baseline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('mfmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='mfmp.mfmp', verbose_name='MFMP')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Escenario MFMP',
                'verbose_name_plural': 'Escenarios MFMP',
            },
        ),
        migrations.AddIndex(
            model_name='mfmp',
            index=models.Index(fields=['entity', 'base_year'], name='mfmp_mfmp_entity__dd6ffc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mfmp',
            unique_together={('entity', 'base_year', 'name')},
        ),
        migrations.AddIndex(
            model_name='mfmpdebtprojection',
            index=models.Index(fields=['mfmp', 'year'], name='mfmp_mfmpde_mfmp_id_aef580_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mfmpdebtprojection',
            unique_together={('mfmp', 'year')},
        ),
        migrations.AddIndex(
            model_name='mfmpexpenseprojection',
            index=models.Index(fields=['mfmp', 'year'], name='mfmp_mfmpex_mfmp_id_5fee1b_idx'),
        ),
        migrations.AddIndex(
            model_name='mfmpexpenseprojection',
            index=models.Index(fields=['concept'], name='mfmp_mfmpex_concept_d3b103_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mfmpexpenseprojection',
            unique_together={('mfmp', 'year', 'concept')},
        ),
        migrations.AddIndex(
            model_name='mfmpincomeprojection',
            index=models.Index(fields=['mfmp', 'year'], name='mfmp_mfmpin_mfmp_id_228c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='mfmpincomeprojection',
            index=models.Index(fields=['concept'], name='mfmp_mfmpin_concept_85bb19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mfmpincomeprojection',
            unique_together={('mfmp', 'year', 'concept')},
        ),
        migrations.AddConstraint(
            model_name='mfmpscenario',
            constraint=models.UniqueConstraint(condition=models.Q(('is_baseline', True)), fields=('mfmp',), name='uniq_mfmp_baseline'),
        ),
        migrations.AlterUniqueTogether(
            name='mfmpscenario',
            unique_together={('mfmp', 'name')},
        ),
    ]
