# Generated by Django 5.0.6 on 2026-04-05 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_restructuring_new_statuses'),
        ('planta', '0004_payrollposition_occupant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_baseline', models.BooleanField(default=False, help_text='Solo un escenario por reestructuración puede ser baseline.', verbose_name='Es línea base')),
                ('cached_metrics', models.JSONField(blank=True, default=dict, help_text='Resultado del último evaluate_scenario. Se invalida al modificar el plan.', verbose_name='Métricas en caché')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parent', models.ForeignKey(blank=True, help_text='Escenario del que se clonó. Nulo si es original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='simulador.scenario', verbose_name='Escenario base')),
                ('payroll_plan', models.ForeignKey(blank=True, help_text='Plan que representa este escenario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='planta.payrollplan', verbose_name='Plan de personal')),
                ('restructuring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.restructuring', verbose_name='Reestructuración')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Escenario',
                'verbose_name_plural': 'Escenarios',
                'indexes': [models.Index(fields=['restructuring'], name='simulador_s_restruc_bd55a2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(condition=models.Q(('is_baseline', True)), fields=('restructuring',), name='uniq_scenario_baseline'),
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together={('restructuring', 'name')},
        ),
    ]
