# Generated by Django 5.0.6 on 2026-04-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_restructuringobjective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('act_reference', models.CharField(blank=True, max_length=255, verbose_name='Acto que lo adoptó')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('source_file_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo importado')),
                ('import_report', models.JSONField(blank=True, default=dict, verbose_name='Reporte de importación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_manuals', to='core.entity', verbose_name='Entidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Manual de funciones vigente',
                'verbose_name_plural': 'Manuales de funciones vigentes',
                'ordering': ['-issue_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegacyManualRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('level', models.CharField(choices=[('DIRECTIVO', 'Directivo'), ('ASESOR', 'Asesor'), ('PROFESIONAL', 'Profesional'), ('TECNICO', 'Técnico'), ('ASISTENCIAL', 'Asistencial')], max_length=16, verbose_name='Nivel')),
                ('code', models.CharField(max_length=8, verbose_name='Código')),
                ('grade', models.CharField(max_length=8, verbose_name='Grado')),
                ('denomination', models.CharField(max_length=255, verbose_name='Denominación')),
                ('main_purpose', models.TextField(blank=True, verbose_name='Propósito principal')),
                ('dependencies_where_applies', models.CharField(blank=True, max_length=500, verbose_name='Dependencias donde aplica')),
                ('min_education', models.TextField(blank=True, verbose_name='Educación mínima')),
                ('min_experience', models.TextField(blank=True, verbose_name='Experiencia mínima')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='manual_legacy.legacymanual', verbose_name='Manual')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Cargo en manual vigente',
                'verbose_name_plural': 'Cargos en manual vigente',
                'ordering': ['manual', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LegacyManualFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_essential', models.BooleanField(default=True, verbose_name='¿Es esencial?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='manual_legacy.legacymanualrole', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Función en manual vigente',
                'verbose_name_plural': 'Funciones en manual vigente',
                'ordering': ['role', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='legacymanual',
            index=models.Index(fields=['entity'], name='manual_lega_entity__28b494_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='legacymanual',
            unique_together={('entity', 'name')},
        ),
        migrations.AddIndex(
            model_name='legacymanualrole',
            index=models.Index(fields=['manual', 'level'], name='manual_lega_manual__f74f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='legacymanualrole',
            index=models.Index(fields=['code', 'grade'], name='manual_lega_code_f5cb15_idx'),
        ),
        migrations.AddIndex(
            model_name='legacymanualfunction',
            index=models.Index(fields=['role'], name='manual_lega_role_id_9e08e5_idx'),
        ),
    ]
