# Generated by Django 5.0.6 on 2026-04-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='committeemeeting',
            new_name='participaci_committ_a9abe1_idx',
            old_name='participaci_committ_date_idx',
        ),
        migrations.RenameIndex(
            model_name='committeemeeting',
            new_name='participaci_restruc_613601_idx',
            old_name='participaci_restr_idx',
        ),
        migrations.RenameIndex(
            model_name='unioncommunication',
            new_name='participaci_restruc_62d0f4_idx',
            old_name='participaci_union_restr_idx',
        ),
    ]
