# Generated by Django 5.0.6 on 2026-04-09 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_assign_levels'),
        ('talento', '0002_employee_cv_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del análisis')),
                ('reference_date', models.DateField(verbose_name='Fecha de referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('restructuring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppression_analyses', to='core.restructuring')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Análisis de supresión',
                'verbose_name_plural': 'Análisis de supresión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuppressionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('employee_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del empleado')),
                ('position_denomination', models.CharField(max_length=255, verbose_name='Denominación del cargo')),
                ('position_code', models.CharField(blank=True, max_length=8, verbose_name='Código')),
                ('position_grade', models.CharField(blank=True, max_length=8, verbose_name='Grado')),
                ('department_name', models.CharField(blank=True, max_length=255, verbose_name='Dependencia')),
                ('appointment_type', models.CharField(choices=[('CARRERA', 'Carrera administrativa'), ('LNR', 'Libre nombramiento y remoción'), ('PROVISIONAL', 'Provisional'), ('TEMPORAL', 'Temporal'), ('TRABAJADOR_OFICIAL', 'Trabajador oficial')], max_length=20, verbose_name='Tipo vinculación')),
                ('years_of_service', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Años de servicio')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario mensual')),
                ('severance_cost', models.DecimalField(decimal_places=2, default=0, help_text='Carrera: 45 días × salario por primer año + 15 días × año adicional.', max_digits=14, verbose_name='Indemnización')),
                ('pending_benefits', models.DecimalField(decimal_places=2, default=0, help_text='Cesantías, vacaciones, prima pendientes.', max_digits=14, verbose_name='Prestaciones pendientes')),
                ('total_suppression_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo total supresión')),
                ('annual_savings', models.DecimalField(decimal_places=2, default=0, help_text='Salario × factor prestacional × 12.', max_digits=14, verbose_name='Ahorro anual')),
                ('break_even_months', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Meses para recuperar')),
                ('has_reten_social', models.BooleanField(default=False, verbose_name='Tiene retén social')),
                ('reten_type', models.CharField(blank=True, max_length=64, verbose_name='Tipo retén')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='indemnizaciones.suppressionanalysis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppression_costs', to='talento.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Costo de supresión',
                'verbose_name_plural': 'Costos de supresión',
                'ordering': ['department_name', 'position_denomination'],
            },
        ),
    ]
