# Generated by Django 5.0.6 on 2026-04-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CONSTITUCION', 'Constitución'), ('LEY', 'Ley'), ('DECRETO', 'Decreto'), ('RESOLUCION', 'Resolución'), ('SENTENCIA_CC', 'Sentencia Corte Constitucional'), ('SENTENCIA_CE', 'Sentencia Consejo de Estado'), ('CONPES', 'Documento CONPES'), ('OTRO', 'Otro')], max_length=16, verbose_name='Tipo')),
                ('reference', models.CharField(help_text='Ej.: Ley 489 de 1998', max_length=128, verbose_name='Referencia')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('summary', models.TextField(verbose_name='Resumen / tema principal')),
                ('key_articles', models.TextField(blank=True, help_text='Artículos o apartes relevantes para el rediseño.', verbose_name='Artículos clave')),
                ('applies_to', models.CharField(blank=True, help_text='Ej.: Territoriales, Orden Nacional, Supresión de empleos…', max_length=255, verbose_name='Aplica a')),
                ('url', models.URLField(blank=True, verbose_name='Enlace oficial')),
            ],
            options={
                'verbose_name': 'Norma o jurisprudencia',
                'verbose_name_plural': 'Base legal',
                'ordering': ['-year', 'kind', 'reference'],
                'indexes': [models.Index(fields=['kind', 'year'], name='legal_legal_kind_8b9bfb_idx')],
            },
        ),
    ]
