# Generated by Django 5.0.6 on 2026-04-04 21:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_entity_approach_entity_current_manual_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('current_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Ingresos corrientes de libre destinación (ICLD)')),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Gastos de funcionamiento')),
                ('personnel_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Gastos de personal')),
                ('law_617_limit_pct', models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Porcentaje máximo de gastos de funcionamiento sobre ICLD según categoría.', max_digits=5, verbose_name='Límite Ley 617/2000 (%)')),
                ('debt_service', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Servicio de la deuda')),
                ('total_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Saldo de la deuda')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='core.entity')),
            ],
            options={
                'verbose_name': 'Año fiscal',
                'verbose_name_plural': 'Años fiscales',
                'ordering': ['entity', 'year'],
                'unique_together': {('entity', 'year')},
            },
        ),
    ]
